apiVersion: 1

datasources:
  - name: PeerMetrics PostgreSQL
    uid: peermetrics-postgres
    type: postgres
    access: proxy
    url: peermetrics-db:5432
    database: peermetrics
    user: peermetrics
    jsonData:
      database: peermetrics
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: peermetrics
    editable: false

